== freemarker-native

link:https://www.graalvm.org/[GraalVM] support for
link:https://freemarker.apache.org/[Apache Freemarker].

NOTE: see xref:#what-it-does[What does this project do] for more information.

link:CHANGELOG.md[image:https://img.shields.io/badge/changelog-Keep%20a%20Changelog%20v1.1.0-%23E05735[Keep
a Changelog v1.1.0 badge]]
https://central.sonatype.com/artifact/org.fugerit.java/freemarker-native[image:https://img.shields.io/maven-central/v/org.fugerit.java/freemarker-native.svg[Maven
Central]]
https://opensource.org/licenses/Apache-2.0[image:https://img.shields.io/badge/License-Apache%20License%202.0-teal.svg[license]]
https://github.com/fugerit-org/fj-universe/blob/main/CODE_OF_CONDUCT.md[image:https://img.shields.io/badge/conduct-Contributor%20Covenant-purple.svg[code
of conduct]]
https://sonarcloud.io/summary/new_code?id=fugerit-org_freemarker-native[image:https://sonarcloud.io/api/project_badges/measure?project=fugerit-org_freemarker-native&metric=alert_status[Quality
Gate Status]]
https://sonarcloud.io/summary/new_code?id=fugerit-org_freemarker-native[image:https://sonarcloud.io/api/project_badges/measure?project=fugerit-org_freemarker-native&metric=coverage[Coverage]]

https://universe.fugerit.org/src/docs/versions/java8.html[image:https://img.shields.io/badge/run%20on-java%208+-%23113366.svg?style=for-the-badge&logo=openjdk&logoColor=white[Java
runtime version]]
https://universe.fugerit.org/src/docs/versions/java11.html[image:https://img.shields.io/badge/build%20on-java%2011+-%23ED8B00.svg?style=for-the-badge&logo=openjdk&logoColor=white[Java
build version]]
https://universe.fugerit.org/src/docs/versions/maven3_9.html[image:https://img.shields.io/badge/Apache%20Maven-3.9.0+-C71A36?style=for-the-badge&logo=Apache%20Maven&logoColor=white[Apache
Maven]]

=== Quickstart

Just add link:https://maven.apache.org/[maven] dependency :

[source,xml]
----
    <dependency>
      <groupId>org.fugerit.java</groupId>
      <artifactId>freemarker-native</artifactId>
      <version>${freemarkerNativeVersion}</version>
    </dependency>
----

Or link:https://gradle.org/[gradle] one :

[source,kts]
----
implementation("org.fugerit.java:freemarker-native:$freemarkerNativeVersion")
----

=== Build

For a local build just run :

[source,shell]
----
gradle build
----

Optionally piblish to local maven repository :

[source,shell]
----
gradle build publishToMavenLocal
----

=== Apache FreeMarker version

FreeMarker Native is currently based on _Apache FreeMarker 2.3.34_.

If a different version is needed, add the Apache FreeMarker dependency before FreeMarker native in link:https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven] :

[source,xml]
----
    <dependency>
      <groupId>org.freemarker</groupId>
      <artifactId>freemarker</artifactId>
      <version>${freemarkerVersion}</version>
    </dependency>
    <dependency>
      <groupId>org.fugerit.java</groupId>
      <artifactId>freemarker-native</artifactId>
      <version>${freemarkerNativeVersion}</version>
    </dependency>
----

[source,kts]
----
implementation("org.freemarker:freemarker:$freemarkerVersion")
implementation("org.fugerit.java:freemarker-native:$freemarkerNativeVersion") {
    exclude("org.freemarker", "freemarker")
}
----
And for link:https://docs.gradle.org/current/userguide/declaring_dependencies.html[Gradle] :


NOTE: for Gradle, latest version always wins, so if you want a specific versions maybe you will need to set some exclusions.

[#what-it-does]
=== What does this project do?

When building with GraalVM a project including link:https://freemarker.apache.org/[Apache FreeMarker], this could lead to errors like :

[source,txt]
----
Error: Class initialization of freemarker.ext.jython.JythonWrapper failed. This error is reported at image build time because class freemarker.ext.jython.JythonWrapper is registered for linking at image build time by command line and command line. Use the option

    '--initialize-at-run-time=freemarker.ext.jython.JythonWrapper'
----

This projects include the necessary link:https://github.com/fugerit-org/freemarker-native/blob/main/src/main/resources/META-INF/native-image/org.fugerit.java/freemarker-native/native-image.properties[configuration] and link:https://github.com/fugerit-org/freemarker-native/blob/main/src/main/java/org/fugerit/java/freemarkernative/Log4jOverSLF4JTesterSubstitute.java[Method substitution] to have it build properly.

[#special-thanks]
=== Special thanks

This project is inspired by the
link:https://quarkus.io/extensions/io.quarkiverse.freemarker/quarkus-freemarker/[quarkus-freemarker] extension (1). I want to thank Quarkus and Quarkus FreeMarker teams.

The main development tool I used is link:https://www.jetbrains.com/idea/download/[IntelliJ IDEA Ultimate].
I want to thank the link:https://www.jetbrains.com/community/opensource/[JetBrains Support for Open-Source Projects program] for providing a license.

NOTE: (1) The main difference between this link:https://github.com/fugerit-org/freemarker-native[FreeMarker native] and link:https://quarkus.io/extensions/io.quarkiverse.freemarker/quarkus-freemarker/[quarkus-freemarker] is that with this project there are only the basic dependencies needed to run link:https://freemarker.apache.org/[Apache Freemarker].
