# CI publish gradle package
#
# version 1.0.0

name: CI publish gradle package

on:
  push:
    branches:
    - branch-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 21
      uses: actions/setup-java@main
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: gradle
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Import gpg
      run: echo -e "${{ secrets.PASSPHRASE }}" | echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --allow-secret-key-import --import
    - name: Build and publish package
      run: gradle clean build publish closeAndReleaseSonatypeStagingRepository -Pprofile:prod --info
      env:
        MAVEN_USERNAME: ${{ secrets.OSS_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSS_PASSWORD }}